# Generated by Django 3.1.7 on 2021-09-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='movie_type',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
