# Generated by Django 3.1.7 on 2021-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_moviedata_movie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/none/none.jpg', upload_to='images/'),
        ),
    ]
